# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &default
  googleKey:  AIzaSyAZL4JU-dvDlSRQg-yKzijBhiQMSmRYnaw
  devise_secret: c209068c1270e570cab96336a15c6f2f39610fb6a019d49e0a2046ec230db53180c991c5a20606290831716f92b8bcbdf036
  secret_key_base: ed415fed6b589737c096547de62e2d1340bcd2367bddb80efda4f8e9fef99d204ff1524c7974ed50341090098aaf71d7615642e64d7433dc7102bc669b187e74
  mail_domain: <%= ENV['MAIL_DOMAIN'] %>
  mail_user: <%= ENV['MAIL_USER'] %>
  mail_password: <%= ENV['MAIL_PASSWORD'] %>
  mail_url: localhost

development:
  <<: *default
  mailchimp_list_id: bfb6b29b79

test:
  <<: *default

deployed: &deployed
  <<: *default
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  devise_secret: <%= ENV['DEVISE_SECRET_KEY'] %>
  googleKey: <%= ENV['GOOGLE_KEY'] %>

staging:
  <<: *deployed
  mail_url: scarpadev.devlits.com
