require 'capistrano/setup'

require 'capistrano/deploy'
require 'capistrano/rvm'
require 'capistrano/bundler'
require 'capistrano/rails'
require 'capistrano/nvm'
require 'capistrano/npm'
require 'airbrussh/capistrano'
require 'slackistrano/capistrano'

Dir.glob('lib/capistrano/tasks/*.rake').each { |r| import r }
