source 'https://rubygems.org'

gem 'rails', '4.2.6'
gem 'pg'

gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails' # TODO: do we need this? revise after React landed to admin
gem 'turbolinks'
gem 'jquery-ui-rails'
gem 'ckeditor'
gem 'react_on_rails', '~> 4'
gem 'autoprefixer-rails'
gem 'simple_calendar', '~> 2.0'

gem 'therubyracer', platforms: :ruby

source 'https://rails-assets.org' do
  gem 'rails-assets-select2', '4.0.2'
  gem 'rails-assets-swiper'
  gem 'rails-assets-tooltipster'
  gem 'rails-assets-Stepper'
  gem 'rails-assets-jquery.ui.touch-punch.dk'
  gem 'rails-assets-jquery-ui'
  gem 'rails-assets-jquery.maskedinput'
end

gem 'jbuilder', '~> 2.0' # TODO: do we need this?

gem 'solidus_backend', '1.2.2'
gem 'solidus_core', '1.2.2'
gem 'solidus_api', '1.2.2'

gem 'solidus_auth_devise', '1.3.0'
gem 'solidus_multi_currency', github: 'whelton/solidus_multi_currency'
gem 'solidus_active_shipping', github: 'solidusio-contrib/solidus_active_shipping'
gem 'paypal-sdk-merchant', '1.106.1'
gem 'solidus_gateway'
gem 'braintree', '~> 2.62.0'

gem 'gibbon'

gem 'prawn-rails'
gem 'barby', require: false
gem 'rmagick', require: false

gem 'logstasher'
gem 'sidekiq'

gem 'letsencrypt_plugin'

gem 'social-share-button'

gem 'acts_as_commentable'

gem 'hashr', '< 2'

gem 'sendgrid-ruby'

group :production, :staging do
  gem 'unicorn'
end

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'meta_request'

  gem 'capistrano'
  gem 'capistrano-bundler', require: false
  gem 'capistrano-rails', require: false
  gem 'capistrano-rvm', require: false
  gem 'capistrano-nvm', require: false
  gem 'capistrano-npm', require: false
  gem 'slackistrano', require: false
  gem 'airbrussh', require: false
end

group :development, :test do
  gem 'quiet_assets'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'

  gem 'fuubar'
  gem 'rspec-rails'
  gem 'factory_girl_rails'
  gem 'capybara'
  gem 'selenium-webdriver'
  gem 'show_me_the_cookies'

  gem 'rubocop', '~> 0.38.0', require: false
  gem 'ruby-lint', require: false
  gem 'scss_lint', require: false

  gem 'pry'
  gem 'pry-nav'
  gem 'pry-doc'
  gem 'pry-rails'
end

group :test do
  gem 'database_cleaner'
  gem 'shoulda-matchers'
  gem 'rspec-given'
  gem 'rspec-retry'
  gem 'launchy'
end
